
# source sampleEpidemic.R
source("./Code/sampleEpidemic.R")

## (Beta, alpha values) would generate the observed data. Remember that we are assuming that there is some
## true underlying epidemic curve that is deterministic and the data we observe are only noisy
## because of sampling/observation error (not because the underlying curve is also

## We assume binomial sampling errors. So we can write the -log-likelihood as the probability of
## observing the observed number positive out of each sample if the prevalence is the value generated by
## a model parameterized by a given set of parameters:

## Return the negative log of likelihood by convention
nllikelihood <- function(parms = disease_params(), obsDat) {
  simDat <- simEpidemic(pop.SI0, parms=parms)
  ## What are the rows from our simulation at which we have observed data?
  matchedTimes <- simDat$time %in% obsDat$time
  nlls <- -dbinom(obsDat$numPos, obsDat$numSamp, prob = simDat$P[matchedTimes], log = T)
  return(sum(nlls))
}


# obsDat= myDat
# nllikelihood(trueParms) ## loglikelihood of the true parameters (which we usually never know)
# nllikelihood(disease_params(Beta = 3, alpha = 1))  ## vs some random guessed parameters



